=== Gvasa/musicLib/xml/albums.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT albums (album*)>

<!ELEMENT album (albumName, artist, year, numTracks, imgUrl, albumUrl)>
<!ATTLIST album ID CDATA #REQUIRED>

<!ELEMENT albumName (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT numTracks (#PCDATA)>
<!ELEMENT imgUrl (#PCDATA)>
<!ELEMENT albumUrl (#PCDATA)>

=== Gvasa/musicLib/xml/albumlib.xml
<?xml version="1.0"?>
<!DOCTYPE albums SYSTEM "albums.dtd">
<?xml-stylesheet type="text/xsl" href="albumlib.xsl"?>
<albums>
  <album ID="133">
    <albumName>Black Holes And Revelations</albumName>
    <artist>Muse</artist>
    <year>2006</year>
    <numTracks>12</numTracks>
    <imgUrl>https://i.scdn.co/image/cc938203606c1673a4e32334967f3621ed6769fe</imgUrl>
    <albumUrl>https://open.spotify.com/album/0lw68yx3MhKflWFqCsGkIs</albumUrl>
  </album>
  <album ID="135">
    <albumName>Discovery</albumName>
    <artist>Daft Punk</artist>
    <year>2001</year>
    <numTracks>14</numTracks>
    <imgUrl>https://i.scdn.co/image/1a9dab25976c706fffccb6bf2cf8a6f5eadd0d29</imgUrl>
    <albumUrl>https://open.spotify.com/album/2noRn2Aes5aoNVsU6iWThc</albumUrl>
  </album>
  <album ID="136">
    <albumName>Meteora</albumName>
    <artist>Linkin Park</artist>
    <year>2003</year>
    <numTracks>13</numTracks>
    <imgUrl>https://i.scdn.co/image/833b73fcf52d97187d891f7d8f77441d52d6927b</imgUrl>
    <albumUrl>https://open.spotify.com/album/4Gfnly5CzMJQqkUFfoHaP3</albumUrl>
  </album>
  <album ID="140">
    <albumName>Magical Mystery Tour</albumName>
    <artist>Beatles</artist>
    <year>1967</year>
    <numTracks>11</numTracks>
    <imgUrl>https://i.scdn.co/image/5779cc9a2ea0d1aa474a6e9575864d6d348acf97</imgUrl>
    <albumUrl>https://open.spotify.com/album/6P9yO0ukhOx3dvmhGKeYoC</albumUrl>
  </album>
  <album ID="141">
    <albumName>The Beatles 1967 - 1970 (Remastered)</albumName>
    <artist>The Beatles</artist>
    <year>1973</year>
    <numTracks>28</numTracks>
    <imgUrl>https://i.scdn.co/image/c0fb10c0253dbd63dc063afb2dedc17922da72bb</imgUrl>
    <albumUrl>https://open.spotify.com/album/5UtlwR5GMEM3XrF8GdzMmB</albumUrl>
  </album>
  <album ID="142">
    <albumName>The Studio Album Collection</albumName>
    <artist>Disturbed</artist>
    <year>2011</year>
    <numTracks>63</numTracks>
    <imgUrl>https://i.scdn.co/image/2bf5c5f012914abcdd30a8fbfd0f8e45bbab5d44</imgUrl>
    <albumUrl>https://open.spotify.com/album/4TdIYEKiTCWlZ0tefxQAH8</albumUrl>
  </album>
  <album ID="143">
    <albumName>(r)Evolution</albumName>
    <artist>Hammerfall</artist>
    <year>2014</year>
    <numTracks>11</numTracks>
    <imgUrl>https://i.scdn.co/image/f193ba4fab937098ac82ab13406c557dba875b49</imgUrl>
    <albumUrl>https://open.spotify.com/album/4nyHlpnIOhn5mmUgpE8LBR</albumUrl>
  </album>
  <album ID="144">
    <albumName>The Discovery</albumName>
    <artist>Born Of Osiris</artist>
    <year>2011</year>
    <numTracks>15</numTracks>
    <imgUrl>https://i.scdn.co/image/0a6d6df89fa6645271b2ac2abfd347ed0366d2e3</imgUrl>
    <albumUrl>https://open.spotify.com/album/3jP8ic7uD7ItxhAwjT6Dxh</albumUrl>
  </album>
</albums>
